Repository iamkaranvalecha/DocuGen, pull requests merged in 2024-11, with the labels that each got.

#54 #53 Process each piece of documentation as it's generated
  src/Core/src/constants.ts
  src/Core/src/docugen.ts
  src/Core/src/index.ts
  src/Core/src/interfaces/IDocumentChunk.ts
  src/Core/src/providers/FileContentProvider.ts
  src/Extensions/VSCode/CHANGELOG.md
  src/Extensions/VSCode/package.json
  src/Extensions/VSCode/releases/docugenai-1.1.0.vsix
  src/Extensions/VSCode/src/extension.ts
Labels: enhancement

#56 Github-action-v1.1.0-stable
  src/Extensions/GithubActions/dist-action/index.js
  src/Extensions/GithubActions/dist-action/index.js.map
  src/Extensions/GithubActions/dist-action/sourcemap-register.js
  src/Extensions/GithubActions/src/main.ts
  src/Extensions/GithubActions/src/providers/utilities.ts
  src/Extensions/GithubActions/src/providers/writefile.ts
Labels: enhancement, Release

#60 #59 🛠️ src/Extensions/GithubActions/src/main.ts -> Added file existence check before processing
  src/Extensions/GithubActions/dist-action/index.js
  src/Extensions/GithubActions/dist-action/index.js.map
  src/Extensions/GithubActions/package.json
  src/Extensions/GithubActions/src/main.ts
Labels: bug
