Repository iamkaranvalecha/DocuGen, pull requests merged in 2024-10, with the labels that each got.

#42 emptied default model settings
  src/Extensions/VSCode/.vscode/extensions.json
  src/Extensions/VSCode/package.json
Labels: bug

#44 documentation file paths fixes
  examples/DocuGen.md
  examples/docugen.json
  src/Extensions/VSCode/src/extension.ts
Labels: bug

#45 Github-actions-fixes
  src/Extensions/GithubActions/dist-action/index.js
  src/Extensions/GithubActions/dist-action/index.js.map
  src/Extensions/GithubActions/package.json
  src/Extensions/GithubActions/src/main.ts
  src/Extensions/GithubActions/src/providers/writefile.ts
Labels: bug, enhancement

#47 Created latest-tag for Github Actions
  .github/workflows/latest-tag.yml
Labels: enhancement

#46 VSCode Extension - Released 1.0.2 version
  src/Extensions/VSCode/package.json
  src/Extensions/VSCode/releases/docugenai-1.0.2.vsix
Labels: Release

#48 🛠️ examples/integration/github-actions.yml -> Updated DocuGen version to latest.
  examples/integration/github-actions.yml
Labels: documentation

#52 Bug/supported extension from user
  src/Extensions/GithubActions/src/main.ts
  src/Extensions/GithubActions/src/providers/utilities.ts
  src/Extensions/VSCode/src/extension.ts
Labels: bug
